language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
before_install:
  - sudo apt-get update
  - sudo apt-get -y install graphviz 
install:
  - pip install --upgrade setuptools
  - pip install -U -r requirements.txt
  - pip install -U -r requirements_dev.txt
  - python setup.py install
script: 
  - pytest tests --cov=supervised/
after_success:
  - coveralls

